name: Build block-biter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Install build tools and libraries required
          sudo apt-get install -y \
            meson \
            ninja-build \
            build-essential \
            cmake \
            git \
            libgl1-mesa-dev \
            xorg-dev \
            libopenal-dev \
            libudev-dev \
            libxi-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxinerama-dev \
            libasound2-dev
          # Install nlohmann-json package available as nlohmann-json3-dev
          sudo apt-get install -y nlohmann-json3-dev

      - name: Build and install Raylib from source
        run: |
          # Clone the raylib repository.
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          # Build for desktop platforms.
          make PLATFORM=PLATFORM_DESKTOP
          # Install the built library.
          sudo make install
          cd ../..

      - name: Configure build directory with Meson
        run: |
          mkdir build
          meson setup build

      - name: Build project with Ninja
        run: meson compile -C build

      - name: List build artifacts
        run: ls -l build
